export const ACCESS_COOKIE_NAME = "matti_access_token";
export const REFRESH_COOKIE_NAME = "matti_refresh_token";
export const COOKIE_NAME = ACCESS_COOKIE_NAME;
export const ACCESS_TOKEN_TTL_MS = 1000 * 60 * 15;
export const REFRESH_TOKEN_TTL_MS = 1000 * 60 * 60 * 24 * 30;
export const ONE_YEAR_MS = 1000 * 60 * 60 * 24 * 365;
export const AXIOS_TIMEOUT_MS = 30_000;
export const UNAUTHED_ERR_MSG = 'Please login (10001)';
export const NOT_ADMIN_ERR_MSG = 'You do not have required permission (10002)';
